
services:
  nginx:
    networks: 
      [mynet]
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    # restart: unless-stopped
    depends_on:
      - wordpress
    # secrets:
    #   - db_root_password
    #   - db_password

  wordpress:
    networks:
      [mynet]
    volumes:
      - ./requirements/wordpress/tools/html:/var/www/html
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    # volumes:
    #   - wp-data:/var/www/html
    depends_on:
        - mariadb
    # secrets:
    #   - wp_password

  mariadb:
    networks:
      [mynet]
    build: requirements/mariadb
    container_name: mariadb

networks:
  mynet:
    driver: bridge